import { ILegalPageData } from "@/components/Legal/types";

export const complaint: ILegalPageData = {
  pageTitle: `Complaint Policy`,
  date: "Apr 5, 2023",
  pageDescr: `
  
  <p style="margin-top:0pt; margin-bottom:8pt; line-height:108%; font-size:12pt;"><strong><span ;">IF YOU ARE UNSATISFIED WITH OUR SERVICES</span></strong></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:108%; font-size:12pt;"><span ;">In such an event, you are of the opinion that your rights and/or interests related to the services provided by us have been violated, you can submit the complaint to us. You must submit the complaint within 3 (three) months from the date when you became or should have become aware about the violation of your rights and/or interests protected by the law.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:108%; font-size:12pt;"><span ;">Your complaint must be made in writing in English language or Russian language and must comprise the following information:&nbsp;</span></p>
<p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="font-family:'Noto Sans Symbols';">●</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span ;">Your data: name, last name or name of the legal entity, registration number (for legal entities only), residence address/registered address, phone number and e-mail address (you must indicate the same email address you registered with us for the purpose of opening of your account);&nbsp;</span></p>
<p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="font-family:'Noto Sans Symbols';">●</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span ;">date of complaint;&nbsp;</span></p>
<p style="margin-top:0pt; margin-left:18pt; margin-bottom:0pt; text-indent:-18pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="font-family:'Noto Sans Symbols';">●</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span ;">your rights and/or interests that were violated and the circumstances in relation thereto; and&nbsp;</span></p>
<p style="margin-top:0pt; margin-left:18pt; margin-bottom:8pt; text-indent:-18pt; text-align:justify; line-height:150%; font-size:12pt;"><span style="font-family:'Noto Sans Symbols';">●</span><span style="width:10.8pt; font:7pt 'Times New Roman'; display:inline-block;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span ;">your request</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">You can submit the complaint directly or via your representative. If the complaint is submitted via the representative, the identity and authorization evidencing documents must follow a copy of an ID/ passport of the authorized person and power of attorney evidencing the right to represent you or any other document evidencing authorization to act on your behalf.&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">Complaint must be submitted via e-mail at the office@stellar.click</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">Complaints that do not comply with the requirements, are submitted in English language or Russian language, are disorder and unreadable, the identity of the applicant is not clear and will not be investigated by us.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">In case the submitted complaint lacks information required for the investigation, we may ask you to eliminate the shortcomings of the complaint by specifying the essence of the complaint or by providing additional documents and/or data required for the proper investigation of your complaint. We will set a reasonable time limit, not shorter than 7 (seven) calendar days, to eliminate the shortcomings of the complaint. You must comply with the deadline set by us. In the event you fulfilled our request for additional data and/or documents, the complaint will be considered to be submitted on the date the shortcomings were eliminated.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">If the complaint does not comply with the requirements and the shortcomings have not been eliminated, Cryptopayments will not investigate the complaint and will return it to you. Such circumstances do not prevent you from contacting us regarding the complaint repeatedly after the identified shortcomings of the complaint are eliminated.</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">&nbsp;</span></p>
<p style="margin-top:0pt; margin-bottom:8pt; text-align:justify; line-height:150%; font-size:12pt;"><span ;">We will handle your complaint and submit the response as soon as possible, but no later than within 15 (fifteen) business days following the day of the receipt of the complaint. In the event beyond our control, we will not be able to submit the response within the specified term, we will submit the interim response to you communicating the reasons of the delay and the term for submission of final response. In all cases, the final response to you will not exceed 35 (thirty-five) business days.</span></p>

  `,
  accordeonContent: [],
};
